eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    username: ${EUREKA_USERNAME:user}
    password: ${EUREKA_PASSWORD:password}
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:user}:${EUREKA_PASSWORD:password}@localhost:8761/eureka/
server:
  port: 8761
spring:
  application:
    name: discovery-server